# Step 1:project introduction

# Interactive Dashboard & KPI Visualizations

## Retail Business Intelligence Dashboard

This project develops an interactive business dashboard using Streamlit and Plotly based on the cleaned retail dataset.

### Dashboard Objectives

- Define and calculate key business KPIs
- Analyze revenue performance
- Calculate Average Order Value (AOV)
- Evaluate customer acquisition metrics where data is available
- Evaluate churn metrics where data is available
- Analyze sales trends
- Analyze category and customer-segment performance
- Provide geographic analysis
- Implement interactive filters
- Implement temporal and categorical drill-down
- Follow professional dashboard visual hierarchy

In [1]:
# STEP 2 — Import libraries

import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# STEP 3 — Load the cleaned dataset

df = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\data\clean_dataset.csv")

print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Rows: 10
Columns: 15

In [3]:
# Step 4: Inspect the dataset

df.head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status,year,month,month_name,gross_sales,discount_amount,net_sales
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2.0,799,10.0,Paid,2026,1,January,1598.0,159.80,1438.20
1,RT-1002,2026-01-09,Fresher,Bengaluru,Course Access,1.0,1499,0.0,Paid,2026,1,January,1499.0,0.00,1499.00
2,RT-1003,2026-01-05,Student,Chennai,Course Access,1.0,1499,0.0,Pending,2026,1,January,1499.0,0.00,1499.00
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3.0,799,5.0,Paid,2026,1,January,2397.0,119.85,2277.15
4,RT-1005,2026-01-09,Fresher,Unknown,Mentor Session,1.0,999,0.0,Failed,2026,1,January,999.0,0.00,999.00

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10 non-null     object
 1   order_date        10 non-null     object
 2   customer_segment  10 non-null     object
 3   city              10 non-null     object
 4   category          10 non-null     object
 5   quantity          10 non-null     float64
 6   unit_price        10 non-null     int64
 7   discount_pct      10 non-null     float64
 8   payment_status    10 non-null     object
 9   year              10 non-null     int64
 10  month             10 non-null     int64
 11  month_name        10 non-null     object
 12  gross_sales       10 non-null     float64
 13  discount_amount   10 non-null     float64
 14  net_sales         10 non-null     float64
dtypes: float64(5), int64(3), object(7)
memory usage: 1.3+ KB

In [5]:
print(df.columns.tolist())

['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status', 'year', 'month', 'month_name', 'gross_sales', 'discount_amount', 'net_sales']

In [6]:
print(df.dtypes)

order_id             object
order_date           object
customer_segment     object
city                 object
category             object
quantity            float64
unit_price            int64
discount_pct        float64
payment_status       object
year                  int64
month                 int64
month_name           object
gross_sales         float64
discount_amount     float64
net_sales           float64
dtype: object

In [7]:
# Step 5: Check the important dashboard columns

print("All columns:")
for column in df.columns:
    print("-", column)

All columns:
- order_id
- order_date
- customer_segment
- city
- category
- quantity
- unit_price
- discount_pct
- payment_status
- year
- month
- month_name
- gross_sales
- discount_amount
- net_sales

In [8]:
# Step 6: Check data quality again

print("Total missing values:")
print(df.isnull().sum())

Total missing values:
order_id            0
order_date          0
customer_segment    0
city                0
category            0
quantity            0
unit_price          0
discount_pct        0
payment_status      0
year                0
month               0
month_name          0
gross_sales         0
discount_amount     0
net_sales           0
dtype: int64

In [9]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
# Step 7: Identify numerical columns

numeric_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Numerical columns:")
print(numeric_columns)

Numerical columns:
['quantity', 'unit_price', 'discount_pct', 'year', 'month', 'gross_sales', 'discount_amount', 'net_sales']

In [12]:
# STep 8: Inspect sales columns

sales_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in ["sales", "revenue", "price", "amount", "quantity"])
]

print("Potential sales-related columns:")
print(sales_columns)

Potential sales-related columns:
['quantity', 'unit_price', 'gross_sales', 'discount_amount', 'net_sales']

In [13]:
# STep 9: Check customer/order information

customer_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in ["customer", "client", "user"])
]

print("Potential customer-related columns:")
print(customer_columns)

Potential customer-related columns:
['customer_segment']

In [14]:
order_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in ["order", "transaction", "invoice"])
]

print("Potential order-related columns:")
print(order_columns)

Potential order-related columns:
['order_id', 'order_date']

# Step 10 :Check whether CAC can actually be calculated

CAC means:

Customer Acquisition Cost

The general calculation is:(CAC = Customer Acquisition Costs / Number of New Customers)

The dataset needs information about acquisition/marketing cost.

In [15]:
cac_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in [
               "acquisition",
               "marketing",
               "campaign",
               "advertising",
               "ad_spend",
               "marketing_cost",
               "acquisition_cost"
           ])
]

print("Potential CAC-related columns:")
print(cac_columns)

Potential CAC-related columns:
[]

In [16]:
# Step 11:Check whether churn can actually be calculated

churn_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in [
               "churn",
               "status",
               "active",
               "inactive",
               "retention"
           ])
]

print("Potential churn-related columns:")
print(churn_columns)

Potential churn-related columns:
['payment_status']

In [17]:
# Step 12: Create an initial KPI calculation

revenue = df["net_sales"].sum()

print("Total Revenue:", revenue)

Total Revenue: 13557.650000000001

In [18]:
# STep 13: Calculate number of transactions

"order_id" in df.columns

True

In [19]:
total_orders = df["order_id"].nunique()

print("Total Orders:", total_orders)

Total Orders: 10

In [20]:
# STep 14: Calculate AOV

#Average Order Value is:AOV = Total Revenue / Total Orders
#If order_id exists:

aov = revenue / total_orders

print("Average Order Value:", round(aov, 2))

Average Order Value: 1355.76

In [21]:
#Step 15: Create a KPI summary

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Total Orders",
        "Average Order Value"
    ],
    
    "Value": [
        revenue,
        total_orders,
        aov
    ]
})

kpi_summary

                   KPI      Value
0        Total Revenue  13557.650
1         Total Orders     10.000
2  Average Order Value   1355.765

In [23]:
# Step 16: Save the KPI summary

kpi_summary.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\kpi_summary.csv",index=False)

print("KPI summary saved successfully.")

KPI summary saved successfully.

In [24]:
# Step 17: Create monthly revenue data

monthly_revenue = (
    df.groupby(["year", "month"])["net_sales"]
      .sum()
      .reset_index()
)

monthly_revenue

   year  month  net_sales
0  2026      1   13557.65

In [25]:
# Create a period

monthly_revenue["period"] = (
    monthly_revenue["year"].astype(str)
    + "-"
    + monthly_revenue["month"].astype(str).str.zfill(2)
)

monthly_revenue

   year  month  net_sales   period
0  2026      1   13557.65  2026-01

In [27]:
# Step 18: Save monthly revenue

monthly_revenue.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\monthly_revenue.csv",index=False)

print("Monthly revenue data saved successfully.")

Monthly revenue data saved successfully.

In [28]:
# Step 19: Create category-level data

category_revenue = (
    df.groupby("category")["net_sales"]
      .sum()
      .reset_index()
      .sort_values("net_sales", ascending=False)
)

category_revenue

         category  net_sales
0   Course Access    7045.30
1    Learning Kit    4514.35
2  Mentor Session    1998.00

In [29]:
category_revenue.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\category_revenue.csv",index=False)

In [30]:
# Step 20: Create customer-segment data

segment_revenue = (
    df.groupby("customer_segment")["net_sales"]
      .sum()
      .reset_index()
      .sort_values("net_sales", ascending=False)
)

segment_revenue

  customer_segment  net_sales
1     Professional    4825.45
2          Student    4735.20
0          Fresher    3997.00

In [31]:
segment_revenue.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\segment_revenue.csv",index=False)

In [32]:
# Step 21: Create geographic data

city_revenue = (
    df.groupby("city")["net_sales"]
      .sum()
      .reset_index()
      .sort_values("net_sales", ascending=False)
)

city_revenue.head(20)

        city  net_sales
1    Chennai    3736.20
0  Bengaluru    2998.00
2      Delhi    2548.30
3  Hyderabad    2277.15
4      Kochi     999.00
6    Unknown     999.00
5     Mumbai       0.00

In [33]:
city_revenue.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\city_revenue.csv",index=False)

In [34]:
# STep 22:Create dashboard-ready dataset

df.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Dashboard_Project\output\dashboard_data.csv",index=False)

print("Dashboard dataset saved successfully.")

Dashboard dataset saved successfully.

# Step 23:Install Streamlit and Plotly

# Now open Anaconda Prompt.

#  sure you're inside:

Retail_Dashboard_Project

# Run:

pip install streamlit plotly

 Wait until installation finishes.

# Then verify:

streamlit --version

# And:

python -c "import plotly; print(plotly.__version__)"

# Step 24: Create the Streamlit application

# Now go to:

 app/

# Create a new file:

app.py

# our structure becomes:

Retail_Dashboard_Project/
│
├── data/
│   └── clean_dataset.csv
│
├── output/
│   ├── kpi_summary.csv
│   ├── monthly_revenue.csv
│   ├── category_revenue.csv
│   ├── segment_revenue.csv
│   ├── city_revenue.csv
│   └── dashboard_data.csv
│
├── app/
│   └── app.py
│
└── Notebook/
    └── Dashboard_Data_Preparation.ipynb

# Step 26: Don't write the entire dashboard yet

This is important.

# Before creating app.py, we need to confirm your actual columns.

# The dashboard code depends on things like:

net_sales
order_id
category
customer_segment
city
year
month

# And especially:

# CAC
# Churn Rate

We shouldn't assume those columns exist.

In [39]:
df[[
    "net_sales",
    "order_id",
    "category",
    "customer_segment",
    "city",
    "year",
    "month"
]]

   net_sales order_id        category customer_segment       city  year  month
0    1438.20  RT-1001    Learning Kit          Student    Chennai  2026      1
1    1499.00  RT-1002   Course Access          Fresher  Bengaluru  2026      1
2    1499.00  RT-1003   Course Access          Student    Chennai  2026      1
3    2277.15  RT-1004    Learning Kit     Professional  Hyderabad  2026      1
4     999.00  RT-1005  Mentor Session          Fresher    Unknown  2026      1
5       0.00  RT-1007  Mentor Session     Professional     Mumbai  2026      1
6    1499.00  RT-1008   Course Access          Fresher  Bengaluru  2026      1
7     799.00  RT-1009    Learning Kit          Student    Chennai  2026      1
8    2548.30  RT-1010   Course Access     Professional      Delhi  2026      1
9     999.00  RT-1011  Mentor Session          Student      Kochi  2026      1

In [38]:
print(df.columns.tolist())

['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status', 'year', 'month', 'month_name', 'gross_sales', 'discount_amount', 'net_sales']

In [40]:
required_columns = [
    "net_sales",
    "order_id",
    "category",
    "customer_segment",
    "city",
    "year",
    "month"
]

print(df[required_columns].head())

   net_sales order_id        category customer_segment       city  year  month
0    1438.20  RT-1001    Learning Kit          Student    Chennai  2026      1
1    1499.00  RT-1002   Course Access          Fresher  Bengaluru  2026      1
2    1499.00  RT-1003   Course Access          Student    Chennai  2026      1
3    2277.15  RT-1004    Learning Kit     Professional  Hyderabad  2026      1
4     999.00  RT-1005  Mentor Session          Fresher    Unknown  2026      1

In [43]:
print(df.columns.tolist())

['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status', 'year', 'month', 'month_name', 'gross_sales', 'discount_amount', 'net_sales']

In [44]:
print("Potential CAC-related columns:")
print(cac_columns)

print("Potential churn-related columns:")
print(churn_columns)

Potential CAC-related columns:
[]
Potential churn-related columns:
['payment_status']

In [45]:
print(df.dtypes)

order_id             object
order_date           object
customer_segment     object
city                 object
category             object
quantity            float64
unit_price            int64
discount_pct        float64
payment_status       object
year                  int64
month                 int64
month_name           object
gross_sales         float64
discount_amount     float64
net_sales           float64
dtype: object

In [46]:
print(df.shape)

(10, 15)